### ISSUE TITLE
Embedded styles don't work

### ISSUE THREAD

**Issue by beeftornado** [adamschwartz/log#33]
If you have styles within styles it doesn't render properly.

eg. `log('_[c="color:red"]ERROR[c]_')` doesn't make the font bold and red as expected. Also doesn't work if you swap the order.

Workaround, `log('[c="color:red;font-weight:bold"]ERROR[c]')`

**Comment by adamschwartz** [comment]
Willing to accept a PR if someone can solve this without needing to bring in a full Markdown parser.

**Comment by adamschwartz** [comment]
Closing for now as `works-as-designed`. Will re-open if someone can show a test case with it working on a range of inputs.
