### ISSUE TITLE
Console.log Backtrace

### ISSUE THREAD

**Issue by mikegrahamjones** [adamschwartz/log#38]
I think it would be neat if the Log provided details of the original SCRIPT 

![javascript_console](https://cloud.githubusercontent.com/assets/923970/16144001/73a4aaca-34c4-11e6-9f0f-1080bb9106cd.png)

I generally tend to use the console as a Debugging Tool, for reading value data and so fourth.

But with the Log.js all console events, originate from **log.js:line** regardless of the originating script.

**Comment by adamschwartz** [comment]
Please see #1
