### ISSUE TITLE
PR: Table Log

### ISSUE THREAD

**Issue by amilajack** [adamschwartz/log#39]
Willing to make a PR for a feature similar to console.table(). Would this pr be welcome?

**Comment by adamschwartz** [comment]
as i understand it, console.table does stuff like this:

![image](https://cloud.githubusercontent.com/assets/154613/16714844/53b5eca2-469d-11e6-8a8f-6de0a6c74a80.png)

what would ur pr do?

**Comment by amilajack** [comment]
I'd make an api that's much more easy to use. So if a user simply logged an object, the output would be something like:
```js
{
 name: 'john',
 age: 43,
 eyeColor: black
}
```

=================================
        Name: john
=================================
        Age: 43
=================================
...so forth.

This is especially useful for arrays of objects.

**Comment by adamschwartz** [comment]
One of the goals of this project is keeping it small. The current version as of the time of this writing is ` 2.13 KB` ([log.min.js @ v0.3.0](https://github.com/adamschwartz/log/blob/794b7219685e3625386ea53454b2e5f5b691b4c0/log.min.js)).

It’s hard to say which PRs I would or wouldn’t accept without seeing them, but I will say that if you can keep the change small yet accomplish a significant improvement over the existing features of `log` and `console.table` for a clear use-case, then I’d certainly consider it. I leave it up to you!

And of course you’re always welcome to fork `log` into something called `console.betterTable` and ship it as an accompanying lib. And if it plays nicely with `log` I’d be happy to list it in the README as an accompanying lib. Good luck!

**Comment by amilajack** [comment]
I see. Thanks for clarifying!
