### ISSUE TITLE
npm version isn't up to date

### ISSUE THREAD

**Issue by liitfr** [adamschwartz/log#40]
Hello Adam !
I didn't know what would be the best place to submit this update request ...

May I ask you why NPM version available isn't the latest ?
Following workaround works fine though : `npm install -S https://github.com/adamschwartz/log` 
The latest NPM version (0.1.5) makes it unusable with Webpack, since it needs following bit of code which is present in v0.3.0

```
  if (typeof define === 'function' && define.amd) {
    define(function() {
      return exportedLog;
    });
```

Anyway thanks for your work !
Mat

**Comment by adamschwartz** [comment]
All set. Thanks for lmk.

**Comment by liitfr** [comment]
Works fine now :sunny: 
thanks !
