### ISSUE TITLE
How to integrate?

### ISSUE THREAD

**Issue by RDIL** [adamschwartz/log#48]
How do i put it on my website?

**Comment by adamschwartz** [comment]
Just include [log.js](https://github.com/adamschwartz/log/blob/master/log.js) (or [log.min.js](https://github.com/adamschwartz/log/blob/master/log.min.js) using a `<script>` tag. That’s it!

**Comment by adamschwartz** [comment]
Just include [log.js](https://github.com/adamschwartz/log/blob/master/log.js) (or [log.min.js](https://github.com/adamschwartz/log/blob/master/log.min.js)) using a `<script>` tag. That’s it!
