### ISSUE TITLE
Chrome error message

### ISSUE THREAD

**Issue by RDIL** [adamschwartz/log#49]
I got this error message from Chrome when trying to import log.js via a <script>:

Refused to execute script from 'https://github.com/adamschwartz/log/blob/master/log.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

I am running newest version of Chrome.

**Comment by adamschwartz** [comment]
That link you shared ([https://github.com/adamschwartz/log/blob/master/log.js](https://github.com/adamschwartz/log/blob/master/log.js)) is a link to _the page_ on Github which displays the source code for this project. You’ll want to point your `<script>` tag at a JavaScript file hosted on the Internet. This can be e.g. a location you upload the file to, or it could be a global CDN location, e.g. [https://unpkg.com/log-with-style@0.3.0/log.js](https://unpkg.com/log-with-style@0.3.0/log.js). I hope this helps!

**Comment by RDIL** [comment]
Oh alright!  Thanks!
